### ISSUE TITLE
Uncategorized From WooCommerce

### ISSUE THREAD

**Issue by nolimitech** [michaeluno/auto-amazon-links-woocommerce-products#1]
### Description

Uncategorized, is pretty much always prioritized when we renew cache. The categories don't always work properly. It puts everything into Uncategorized. 

Theme Used: Top Store

### Steps to reproduce

1. After doing the steps from here: [https://github.com/michaeluno/auto-amazon-links-woocommerce-products](url)
2. Inside Woo Commerce --> Products --> Categories --> Watch the names and the count inside the categories.
3. We need to Edit the name manually, before remaking another category from Auto Amazon Links, because it'll put all products from all categories into the Uncategorized.

It worked fine, the first time. But the Second and Third time, it's all mixed into Uncategorized.

### Environment

Auto Amazon Links. Version 5.2.7
Auto Amazon Links - WooCommerce Products (Beta). Version 0.2.0
Auto Amazon Links Pro. Version 4.1.1
WooCommerce. Version 6.4.1
WooCommerce Cart Add-Ons. Version 2.1.0

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that the problem occurs with the default theme and all the plugins deactivated except "Auto Amazon Links".

No

**Comment by michaeluno** [comment]
Hi,

I cannot reproduce the problem. It might depend on the unit type. For Product Search units, products will be uncategorized as there is no category information provided from the Amazon side. For Category and PA-API units, categories should be converted as well.

So which unit type is it? A screenshot of the unit listing table would be helpful.

**Comment by nolimitech** [comment]
Hello,

I took Unit by Category. (I don't use PA-API, right now).

I did a reset. And now, nothing work.
I took a screenshot of everything I did.

Step1: Here is my active plugins.
![ActivePlugins](https://user-images.githubusercontent.com/3926190/167316779-f259d076-4fcf-4408-9d0f-c1a8b76bea4a.png)

Step2: Add Unit by Category
![Step2_AddUnitByCategory](https://user-images.githubusercontent.com/3926190/167316807-27aca61f-f21d-4404-9f18-8242a703d426.png)

Step3:  Create the Category
![Step3_CreateCategory](https://user-images.githubusercontent.com/3926190/167316864-5c9e0e86-a132-4b34-9d19-602a10c33aa6.png)

Step4: Check WooCommerce Product Converter
![Step4_CheckWooCommerceProductConverter](https://user-images.githubusercontent.com/3926190/167316881-0fb4e1f1-077d-45a0-a1ea-7b7c95ddd8ed.png)

Step5: Manage Unit --> Check the category --> Renew Cache
![Step5_RenewCache](https://user-images.githubusercontent.com/3926190/167316896-1695d980-6256-4cbb-b970-e461fbdb7eee.png)

Step6: Inside Products Tabs --> Categories
![Step6_Products_Categories](https://user-images.githubusercontent.com/3926190/167316910-b730bcb8-fdee-46ec-9982-88d175478df8.png)

Nothing is inside the categories. 
Last time i wrote, everything was inside the Uncategorized, every time i added a category.

Hope this can help.
PS: Sorry, if my answer are late, I'm pretty busy right now.

NLT

**Comment by michaeluno** [comment]
I'm not sure why you have such a problem. This plugin has been updated by the way and you are using v0.2.0. Can you try the latest version 1.0.0?

**Comment by nolimitech** [comment]
I just thought about something. Which version of php do you use? My last
try, I upgraded to 8.0. I'll.try with the last version I had when I tried
the first time.

Le dim. 8 mai 2022, 20 h 05, Michael Uno ***@***.***> a
écrit :

**Comment by michaeluno** [comment]
I cannot reproduce it with PHP 8. The PHP version in my main development environment is 7.4. 

Try the latest version 1.0.0 first. If it still doesn't work, enable the site debug mode and post relevant debug.log outputs.

**Comment by nolimitech** [comment]
Ok, I'll try tomorrow. Right now, I don't know why, but the categories
search doesn't work. I'll try to debug, didn't the plugin had the option,
haha, maybe I'll see something on my side with wordpress.

Le lun. 9 mai 2022, 22 h 56, Michael Uno ***@***.***> a
écrit :
