### ISSUE TITLE
Hi,  I have 3 questions.

### ISSUE THREAD

**Issue by 11112121ad** [michaeluno/auto-amazon-links-woocommerce-products#13]
### Description

1. how to add buy now button inside the red box
![add buy now button](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/assets/168655084/3b3fd431-5230-49c9-ae1d-8ca5432f087e)

3. after I  Convert Unit to WooCommerce Product, all previous added woocommerce products in my site have added  (as of n/a - More info) after the price. How to remove it. I only need to remove (as of n/a - More info) from Non-Amazon products，Products converted from Amazon should retain this   (as of n/a - More info) 
![as of na - More info_副本](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/assets/168655084/d59e1fee-8f19-4598-bdd2-75f4e72fc31d)

5. how to add all images of the amazon product to woocommerce product.
![add all product image](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/assets/168655084/18e287c7-a9fc-416f-ab94-192a30957a60)

thank you

### Images

1

### Please confirm that you have searched existing issues in this repository.

Yes

**Comment by michaeluno** [comment]
Hi,

Please keep one question per topic with a title that represents the problem. This is important to track issues as well as help others find the information they are looking for.  

For the second question, [this topic](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/issues/6) should help.
