### ISSUE TITLE
Error Auto Amazon Links: No products found

### ISSUE THREAD

**Issue by jhdscript** [michaeluno/auto-amazon-links-woocommerce-products#2]
### Description

Hello,

When I m writing an article i use shortcut to include amazon ads in Elementor.

I use this shortcode (or similars) : [amazon_auto_links country=”FR” count=”1″ description_length=”300″ credit_link=”0″ asin=”B0973BWCCZ”]

I obtain these error : Error Auto Amazon Links: No products found

I try to clear cache but same issue.

I realize less than 350 queries to api.

Any help will be appreciated because sometimes it works

### Steps to reproduce

Use multiple code like : [amazon_auto_links country=”FR” count=”1″ description_length=”300″ credit_link=”0″ asin=”B0973BWCCZ”]

### Please confirm that you have searched existing issues in this repository.

Yes

### Please confirm that the problem occurs with the WooCommerce default theme, [StoreFront](https://wordpress.org/themes/storefront/) and all the plugins deactivated except "Auto Amazon Links" and "Auto Amazon Links - WooCommerce Products".

Yes

**Comment by michaeluno** [comment]
It appears this is an issue of Auto Amazon Links. Please post this on the [issue tracker](https://github.com/michaeluno/amazon-auto-links/issues) of it. 

Thank you.
