### ISSUE TITLE
Problems with Amazon Links – WooCommerce Products

### ISSUE THREAD

**Issue by regianesouzaatelie** [michaeluno/auto-amazon-links-woocommerce-products#3]
### Description

Please, I need help with: https://ofertasdaregi.com.br/p/

I’m using the Amazon Auto Links and Auto Amazon Links – WooCommerce Products (Converts unit products to WooCommerce products. Versão 1.0.0 ) in my site. This is importing very well to units, but I have some questions about Amazon Links – WooCommerce Products.

Links of the imported units: 
https://ofertasdaregi.com.br/amazon_auto_links/pesquisa/
https://ofertasdaregi.com.br/amazon_auto_links/categorias/

Please, check the image attached
Number 2 and 3 on the image: When I hability the Amazon Links – WooCommerce Products:

* Some products get incorrectly price, because the plugin is not considering the comma in the “price field” from woocomerce. So, the product that costs 93.90 becomes 9390.

* In the some products the plugin does not fill in the promotional price field or fills it with “zero (0)”. So, either the product has the wrong price (old price) or the product has a zero price.

* Is it possible that the link of the button sending to the product page on Amazon site? In my site the button is sending to cart, because o plugin doesn’t format the product like external/affiliate product, it is formating like simple product (image 3 and 4). So, I’ need to adjusting manually all these details in each products.

* Image 2: Is it possible format the message (as of Jul 31, 2023 21:51 GMT -03:00 – More info) to get as “Offer posted 4 hours ago - More info” (for exemple)? Is it possible change the font, size and style of this? I'm from Brazil, so I would like formating the message in Portuguese.

* It it possible to change the image showed in shop page? Because, ever I upload the image to feautured field it showed not on that page.

Please, I would like get some help, because I’ need to adjusting manually all these details in each products. Thanks very much.

### Images

![image1](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/assets/141432647/5e62e379-315c-4105-83be-e936c4ef6f75)

### Please confirm that you have searched existing issues in this repository.

Yes

**Comment by michaeluno** [comment]
Hi, 

> Some products get incorrectly price, because the plugin is not considering the comma in the “price field” from woocomerce. So, the product that costs 93.90 becomes 9390.

It seems a bug. Could you create a bug report? Thanks.

> In the some products the plugin does not fill in the promotional price field or fills it with “zero (0)”. So, either the product has the wrong price (old price) or the product has a zero price.

I'm not sure whether I understand what is described. It could be a bug so please create a bug report about this. This requires more detailed descriptions especially about promotional price field as I don't get what it refers to.

> Is it possible that the link of the button sending to the product page on Amazon site? In my site the button is sending to cart, because o plugin doesn’t format the product like external/affiliate product, it is formating like simple product (image 3 and 4). So, I’ need to adjusting manually all these details in each products.

Not possible with the current design. Could you create a feature request about this?

> Image 2: Is it possible format the message (as of Jul 31, 2023 21:51 GMT -03:00 – More info) to get as “Offer posted 4 hours ago - More info” (for exemple)? Is it possible change the font, size and style of this? I'm from Brazil, so I would like formating the message in Portuguese.

You need to translate the plugin. To do so, grab the [base language file](https://plugins.svn.wordpress.org/amazon-auto-links/trunk/language/amazon-auto-links.pot) and start translating using [POEdit](https://poedit.net/) or something. When it's done, from this [page](https://translate.wordpress.org/projects/wp-plugins/amazon-auto-links/stable/) find _Portuguese (Brazil)_ and open that page. At the bottom you can upload your translated .po file (you need to log in to see that link). Upload it and wait for those translated items are accepted by the WordPress translation team. If the translation coverage reaches a certain percentage, your site automatically downloads your language file of the plugin and shows the translated text.

> It it possible to change the image showed in shop page? Because, ever I upload the image to feautured field it showed not on that page.

Not possible with the current design. Could you create a feature request? 

---

Please keep in mind that it is important to separate topics in each issue to help keep track on them. Thank you.

**Comment by regianesouzaatelie** [comment]
Hi Michaeluno, thanks for returning.

1.
> It seems a bug. Could you create a bug report? Thanks.
[logs.txt](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/files/12283271/logs.txt)

Plese, verify if the "error logs" is enought to this question (Some products get incorrectly price, because the plugin is not considering the comma in the “price field” from woocomerce. So, the product that costs 93.90 becomes 9390.)

2.
> I'm not sure whether I understand what is described. It could be a bug so please create a bug report about this. This requires more detailed descriptions especially about promotional price field as I don't get what it refers to.

About that, I mean... "Promotional price field", it would be like a "discount product price".

When I convert unit of products to WooCommerce products, In the some products the "promotional price field" is not filled with no value or then, it is filled with “zero (0) ”. So, the product has the a wrong price because "the field discount product price" or "promotional price" is not filled with no value.

Please see the image 
![image2](https://github.com/michaeluno/auto-amazon-links-woocommerce-products/assets/141432647/37295809-e14c-4b6c-a829-3ed88d4835c4)

3.
> Not possible with the current design. Could you create a feature request about this?
about (Is it possible that the link of the button sending to the product page on Amazon site?)

How or where can I do it? Can you give some informations about?

4.
> You need to translate the plugin. To do so, grab the [base language file](https://plugins.svn.wordpress.org/amazon-auto-links/trunk/language/amazon-auto-links.pot) and start translating using [POEdit](https://poedit.net/) or something. When it's done, from this [page](https://translate.wordpress.org/projects/wp-plugins/amazon-auto-links/stable/) find _Portuguese (Brazil)_ and open that page. At the bottom you can upload your translated .po file (you need to log in to see that link). Upload it and wait for those translated items are accepted by the WordPress translation team. If the translation coverage reaches a certain percentage, your site automatically downloads your language file of the plugin and shows the translated text.

All right, I will try. 
However... Is it possible disable this message to shop page?

5.
> Not possible with the current design. Could you create a feature request?
about (It it possible to change the image showed in shop page? Because, ever I upload the image to feautured field it showed not on that page)

Some explication about that:
I need the image on the  feautured field because I send all the product posts to Telegram by another plugin. 
So, is it possible to get the image in the  feautured field? So, my problem would be resolved, because I need upload the image in the  feautured field in each products

.....................................

I'm sorry if some questions is not very well clear. My English is not suficient good.
Thanks so much.

**Comment by michaeluno** [comment]
To submit a feature request, find the _New Issue_ button at the top right corner and click it. In the following page, find the _Feature Request_ row and click on _Get Started_. Submitting a bug report can be done in the same way. 

For further questions, just create a new topic each. Don't worry about whether it becomes a lot of new threads.
